name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Show available Xcode versions
      run: ls -la /Applications/ | grep Xcode
    
    - name: Show current Xcode version
      run: xcodebuild -version
    
    - name: List available simulators
      run: xcrun simctl list devices available
    
    - name: Cache Swift packages
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
          ~/.cache/org.swift.swiftpm
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-smp-
    
    - name: Validate project
      run: xcodebuild -list -project ios-otel-demo-app-to-devrel-demo.xcodeproj
    
    - name: Build and run unit tests
      run: |
        xcodebuild \
          -project ios-otel-demo-app-to-devrel-demo.xcodeproj \
          -scheme ios-otel-demo-app-to-devrel-demo \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          -only-testing:ios-otel-demo-app-to-devrel-demoTests \
          clean test \
          CODE_SIGNING_ALLOWED=NO
    
    - name: Build app for simulator
      run: |
        xcodebuild \
          -project ios-otel-demo-app-to-devrel-demo.xcodeproj \
          -scheme ios-otel-demo-app-to-devrel-demo \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          clean build \
          CODE_SIGNING_ALLOWED=NO

  ui-tests:
    runs-on: macos-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache Swift packages
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
          ~/.cache/org.swift.swiftpm
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-smp-
    
    - name: Run UI tests
      run: |
        xcodebuild \
          -project ios-otel-demo-app-to-devrel-demo.xcodeproj \
          -scheme ios-otel-demo-app-to-devrel-demo \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          -only-testing:ios-otel-demo-app-to-devrel-demoUITests \
          clean test \
          CODE_SIGNING_ALLOWED=NO